version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.4-alpine
    container_name: arc-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: arc_user
      POSTGRES_PASSWORD: arc_local_dev_password
      POSTGRES_DB: arc_blog
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U arc_user -d arc_blog"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
